import './globals.css';
import { ubuntu } from './ui/fonts';
import Header from './ui/Header';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${ubuntu.className}`}>
        <Header />
        <main className='px-5'>{children}</main>
        <footer>
          <div>
            <h2>Send me What on your mind</h2>
            <form></form>
          </div>
          <div>
            <h2>Find me on</h2>
          </div>
        </footer>
      </body>
    </html>
  );
}
